- hosts: localhost
  connection: local
  vars:
    dbuser: "testuser"
    dbpass: "badpasss"
    dbname: "testdb"
  tasks:
    - name: Install git
      apt:
        name: git
      become: yes

    - include: postgres.yml
    - include: ruby.yml
    - include: nodejs.yml
    - include: wpcs2.yml
    - include: on_vagrant.yml
